// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_WC-EyVCnVgyJrSEiuR6IMYk1ADa23Q4',
    appId: '1:676294067478:web:02674833553bdb6a96bc37',
    messagingSenderId: '676294067478',
    projectId: 'jklf-aa08d',
    authDomain: 'jklf-aa08d.firebaseapp.com',
    databaseURL: 'https://jklf-aa08d-default-rtdb.firebaseio.com',
    storageBucket: 'jklf-aa08d.appspot.com',
    measurementId: 'G-LMYQBHRVM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqkXF8qTBc2VJt9enLJkDxZs1cVRUYKV0',
    appId: '1:676294067478:android:cf16b68b9e59ca2596bc37',
    messagingSenderId: '676294067478',
    projectId: 'jklf-aa08d',
    databaseURL: 'https://jklf-aa08d-default-rtdb.firebaseio.com',
    storageBucket: 'jklf-aa08d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHKKohjRkALg7A6T4EaYDImRgMCh89wGg',
    appId: '1:676294067478:ios:c8c6265316c205ef96bc37',
    messagingSenderId: '676294067478',
    projectId: 'jklf-aa08d',
    databaseURL: 'https://jklf-aa08d-default-rtdb.firebaseio.com',
    storageBucket: 'jklf-aa08d.appspot.com',
    iosClientId: '676294067478-8oelq09uvccdrm18jjhevb59j31527bu.apps.googleusercontent.com',
    iosBundleId: 'com.example.jkl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHKKohjRkALg7A6T4EaYDImRgMCh89wGg',
    appId: '1:676294067478:ios:c8c6265316c205ef96bc37',
    messagingSenderId: '676294067478',
    projectId: 'jklf-aa08d',
    databaseURL: 'https://jklf-aa08d-default-rtdb.firebaseio.com',
    storageBucket: 'jklf-aa08d.appspot.com',
    iosClientId: '676294067478-8oelq09uvccdrm18jjhevb59j31527bu.apps.googleusercontent.com',
    iosBundleId: 'com.example.jkl',
  );
}
