/// Flutter icons MyFlutterApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const _kFontFam1 = 'MyFlutterApp1';
  static const String? _kFontPkg = null;

  static const IconData search =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData umpire =
      IconData(0xe804, fontFamily: _kFontFam1, fontPackage: _kFontPkg);
  static const IconData eating =
      IconData(0xe805, fontFamily: _kFontFam1, fontPackage: _kFontPkg);
  static const IconData location =
      IconData(0xe802, fontFamily: _kFontFam1, fontPackage: _kFontPkg);
  static const IconData navigate =
      IconData(0xe803, fontFamily: _kFontFam1, fontPackage: _kFontPkg);
}
