// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcYWXOeJGrICjCAr9iuscZJ0bVxvQES_Q',
    appId: '1:509242961142:web:3cfe8421a9e14aee42d0d7',
    messagingSenderId: '509242961142',
    projectId: 'home-construction-8f2e1',
    authDomain: 'home-construction-8f2e1.firebaseapp.com',
    storageBucket: 'home-construction-8f2e1.appspot.com',
    measurementId: 'G-4Y809REDZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPdQSmLUWl2cNNUUUOmDDda0L311iDVzs',
    appId: '1:509242961142:android:762c0aeffb10893842d0d7',
    messagingSenderId: '509242961142',
    projectId: 'home-construction-8f2e1',
    storageBucket: 'home-construction-8f2e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBslz-f5UCAtCH9wJkS5YsqSaaGmaIr-rY',
    appId: '1:509242961142:ios:0238bca5dec5530842d0d7',
    messagingSenderId: '509242961142',
    projectId: 'home-construction-8f2e1',
    storageBucket: 'home-construction-8f2e1.appspot.com',
    iosClientId: '509242961142-jl0c5hmu8mf5nurd5926cn0n9mp2edeg.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeConstruction',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBslz-f5UCAtCH9wJkS5YsqSaaGmaIr-rY',
    appId: '1:509242961142:ios:0238bca5dec5530842d0d7',
    messagingSenderId: '509242961142',
    projectId: 'home-construction-8f2e1',
    storageBucket: 'home-construction-8f2e1.appspot.com',
    iosClientId: '509242961142-jl0c5hmu8mf5nurd5926cn0n9mp2edeg.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeConstruction',
  );
}
