// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7Zad7FuzCEkMDUHoMlVzRIjxg16FqPvQ',
    appId: '1:633431337358:web:edfecd00070e443dec5cdf',
    messagingSenderId: '633431337358',
    projectId: 'urban-rider-942ff',
    authDomain: 'urban-rider-942ff.firebaseapp.com',
    databaseURL: 'https://urban-rider-942ff-default-rtdb.firebaseio.com',
    storageBucket: 'urban-rider-942ff.appspot.com',
    measurementId: 'G-XZPWJFLN2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDftkl5W0BMMElCjOa9qzzsoyWYRU5QbPg',
    appId: '1:633431337358:android:a597903287b2f162ec5cdf',
    messagingSenderId: '633431337358',
    projectId: 'urban-rider-942ff',
    storageBucket: 'urban-rider-942ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgVNtSiRiu6ZEcQKnbKEol2jNNlx5Wm_o',
    appId: '1:633431337358:ios:a310a4cbbc2bd9f1ec5cdf',
    messagingSenderId: '633431337358',
    projectId: 'urban-rider-942ff',
    storageBucket: 'urban-rider-942ff.appspot.com',
    iosClientId: '633431337358-n2qa35crvdnp6qbbav8eul739ctn9a78.apps.googleusercontent.com',
    iosBundleId: 'com.example.urbanRider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgVNtSiRiu6ZEcQKnbKEol2jNNlx5Wm_o',
    appId: '1:633431337358:ios:a310a4cbbc2bd9f1ec5cdf',
    messagingSenderId: '633431337358',
    projectId: 'urban-rider-942ff',
    storageBucket: 'urban-rider-942ff.appspot.com',
    iosClientId: '633431337358-n2qa35crvdnp6qbbav8eul739ctn9a78.apps.googleusercontent.com',
    iosBundleId: 'com.example.urbanRider',
  );
}
